# Template netplan for static ip
network:
  renderer: networkd
  ethernets:
    <iface>:
      link-local: [ ipv4 ]
      dhcp4: false
      addresses: [ <ip/subnet> ]
      gateway4: <ip-gateway>
      nameservers:
        addresses: [ 1.1.1.1 ]
  version: 2
