# --------------------------------------------------
# MINIMAL SETUP SHELL FOR TERMUX INCLUDE COLORIZING.
# --------------------------------------------------
# Less features you set
# More skills you'll get.
# --->>
# Property of arfanamd.
# Last edited: Sat Apr  6 21:45:58 WIB 2024
# Termux     : v.0.117 (official f-droid version)
# --------------------------------------------------

# Nonexist commands handler.
# If user has entered command which invokes non-available
# utility, command-not-found will give a package suggestions.
if [[ -x /data/data/com.termux/files/usr/libexec/termux/command-not-found ]]; then
	command_not_found_handle() {
		printf "\e[38;5;187m"
		/data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"
		printf "\e[0m\n"
	}
fi

# Command history tweaks:
# - Append history instead of overwriting
#   when shell exits.
# - When using history substitution, do not
#   exec command immediately.
# - Do not save duplicated commands.
shopt -s histappend
shopt -s histverify
export HISTCONTROL=erasedups

# Default time format for history (optional).
# The format use "date" command format.
export HISTTIMEFORMAT='%g%m%d:%H:%M '

# Default text editor.
export VISUAL='vi'

# Default pager (text viewer)
export PAGER='less --use-color -DdB -Dug -DPKb -~'

# Fix no color when using man
export GROFF_NO_SGR=1

# Auto-correct for directory name misspelling/typo.
shopt -s cdspell

# Warn the user when they're trying to exit while there's
# jobs running in the background.
shopt -s checkjobs

# Set current session information to window title.
printf "\e]0; ${1:-🐧 %s - %s} \007" "$(date +'%d/%m/%y - %H:%M %Z')" "${SHLVL}"

# Default path wrapper in command prompt.
export PROMPT_DIRTRIM=2

# Some color set
export LS_COLORS='no=00:fi=00:di=1;34:ln=1;95:or=1;41;95:mi=00:pi=31:so=93:bd=1;44;97:cd=1;44;97:ex=92:su=42:sg=42:st=42:tw=1;102;90:ow=42:*.tar.gz=1;91:*.tar.bz=1;91:*.tar.xz=1;91:*.tgz=1;91:*.tbz=1;91:*.zip=1;91:*.rar=1;91:*.bz2=1;91:*.deb=1;91:*.rpm=1;91:*.jar=1;91:*.gz=1;91:*.bz=1;91:*.xz=1;91:*.7z=1;91:*.jpeg=1;96:*.svg=1;96:*.png=1;96:*.gif=1;96:*.jpg=1;96:*.ico=1;96:*.webm=1;96:*.mp4=1;96:*.mkv=1;96:*.avi=1;96:*.mp3=1;96:*.ogg=1;96:*.wav=1;96:*.bak=47;90:*.old=47;90:*.swp=47;90:*.ori=47;90:';

# Git prompt attribute
export GIT_PS1_SHOWDIRTYSTATE=1        # '*' unstaged, '+' staged
export GIT_PS1_SHOWSTASHSTATE=1        # '$' sign
export GIT_PS1_SHOWUNTRACKEDFILES=1    # '%' sign
export GIT_PS1_SHOWUPSTREAM="auto"     # '<' behind, '>' ahead, '=' no diff, '<>' diverged

# Shell prompt
export PS1="\e[0m•\$([[ \$? != 0 ]] && printf \"\e[1;91m✖\e[0m\")•\e[1;38;5;43mspens\e[0m:\e[38;5;7m\w\e[1;38;5;072m \$(__git_promptPS1)\e[0m\n╰► "
export PS2='▶ '

# Enable user plugins
if [[ -d /data/data/com.termux/files/home/.profile.d/ ]]; then
	for src in /data/data/com.termux/files/home/.profile.d/*; do
		source "${src}"
	done
fi

# Add user local binary to the PATH variable
if [[ -d /data/data/com.termux/files/home/.sbin/ ]]; then
	export PATH="${PATH}:/data/data/com.termux/files/home/.sbin/"
fi

# Enable standard key binding for ctrl-s and ctrl-q, used for
# suspend (ctrl-s) and unsuspend (ctrl-q) the output.
# To disable it, change the argument to "-ixon".
stty ixon

# Use a vi-style to interact with terminal instead of emacs-style.
#set -o vi

# vim:foldmethod=marker:ts=4:ft=bash
